#!/usr/bin/env ruby

files = Dir['languages/*/Dockerfile']

languages = ARGV

files.each do |file|
  language = file.split('/')[1]
  if languages.empty? || languages.include?(language)
    puts "\n########## Install #{language} ##########\n\n"
    system("docker build -t ubuntu:#{language} ./languages/#{language}")
    if language == "java"
      system("./fixed_java_install.rb")
    end
  end
end
